In [1]:
import tushare as ts
import pandas as pd
ts.set_token('047e2bcae2ea6c2f6f225eeb62087d27e1981988e758c82ba1997971')

In [2]:
pro = ts.pro_api()


#获取可转债发行数据
df = pro.cb_issue(ts_code='110031.SH')


#获取可转债发行数据，自定义字段
# df = pro.cb_issue(fields='ts_code,ann_date,offl_deposit')

ConnectTimeout: HTTPConnectionPool(host='api.waditu.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x122fdcf10>, 'Connection to api.waditu.com timed out. (connect timeout=30)'))

In [27]:
df

,ts_code,ann_date,res_ann_date,plan_issue_size,issue_size,issue_price,issue_type,onl_code,onl_name,onl_date,...,onl_pch_excess,shd_ration_code,shd_ration_name,shd_ration_date,shd_ration_record_date,shd_ration_pay_date,shd_ration_price,shd_ration_ratio,shd_ration_size,offl_size
0,110031.SH,20150610,20150617,None,24.0,100.0,"优先配售,网上定价和网下配售",733271,航信发债,20150612,...,3104.32,704271,航信配债,20150612,20150611,20150612,100.0,2.599,19319730.0,4595520.0

In [14]:
df[df.ann_date > '20200815']

Empty DataFrame
Columns: [ts_code, ann_date, offl_deposit]
Index: []

In [36]:
df1 = pro.cb_daily(ts_code='110031.SH', start_date='20200719')

In [51]:
df2 = pro.cb_daily(start_date='20200810')

In [52]:
df2.describe()

,pre_close,open,high,low,close,change,pct_chg,vol,amount
count,1444.000000,1444.00000,1444.000000,1444.000000,1444.000000,1444.000000,1444.000000,1.444000e+03,1444.000000
mean,137.887452,138.24876,142.604107,134.721558,138.110630,0.223179,0.193256,1.261264e+05,23009.941444
std,68.855841,69.81405,74.940535,65.944933,68.884793,8.469825,4.444283,3.286237e+05,65476.160706
min,79.420000,0.00000,0.000000,0.000000,79.420000,-62.900000,-16.800500,0.000000e+00,0.000000
25%,112.680000,112.98750,114.322500,112.000000,113.000000,-1.420000,-1.083625,7.995975e+03,921.542425
50%,122.500000,122.90000,125.000000,120.545000,122.215000,-0.010000,-0.008250,2.381100e+04,3000.463150
75%,140.720000,140.96750,145.530000,136.742500,139.755000,0.912500,0.748675,8.430850e+04,12673.335125
max,1038.000000,1045.00000,1098.000000,1021.280000,1029.900000,90.200000,72.180300,4.235190e+06,613124.420300

In [39]:
pd.concat([df1, df2], axis=0)

,ts_code,trade_date,pre_close,open,high,low,close,change,pct_chg,vol,amount
0,110031.SH,20200814,112.82,112.36,113.37,112.36,112.70,-0.12,-0.1064,1974.0,222.9056
1,110031.SH,20200813,112.42,112.78,112.99,112.53,112.82,0.40,0.3558,1690.0,190.4889
2,110031.SH,20200812,112.69,112.80,113.17,112.30,112.42,-0.27,-0.2396,2832.0,319.3778
3,110031.SH,20200811,113.00,113.40,113.95,112.61,112.69,-0.31,-0.2743,4268.0,484.2775
4,110031.SH,20200810,112.49,112.99,114.12,112.70,113.00,0.51,0.4534,2534.0,287.1339
5,110031.SH,20200807,112.70,112.61,112.96,111.98,112.49,-0.21,-0.1863,3814.0,428.6201
6,110031.SH,20200806,112.30,112.20,113.10,112.03,112.70,0.40,0.3562,7683.0,864.4342
7,110031.SH,20200805,112.06,112.20,112.79,112.00,112.30,0.24,0.2142,8341.0,936.9653
8,110031.SH,20200804,112.77,112.99,113.09,111.82,112.06,-0.71,-0.6296,17033.0,1909.7207
9,110031.SH,20200803,113.00,113.50,114.51,112.66,112.77,-0.23,-0.2035,18007.0,2040.3026
10,110031.SH,20200731,111.84,112.29,113.93,111.80,113.00,1.16,1.0372,7348.0,825.2937
11,110031.SH,20200730,113.29,113.57,114.00,111.70,111.84,-1.45,-1.2799,3986.0,448.8838
12,110031.SH,20200729,112.97,112.41,115.88,112.39,113.29,0.32,0.2833,10192.0,1161.4125
13,110031.SH,20200728,111.45,111.98,116.00,111.85,112.97,1.52,1.3638,10191.0,1160.6050
14,110031.SH,20200727,112.56,112.74,112.76,111.11,111.45,-1.11,-0.9861,6673.0,744.3474
15,110031.SH,20200724,113.31,113.39,113.88,111.10,112.56,-0.75,-0.6619,14527.0,1638.2083
16,110031.SH,20200723,114.54,114.01,114.40,112.45,113.31,-1.23,-1.0739,3829.0,433.4366
17,110031.SH,20200722,115.01,114.90,115.78,114.01,114.54,-0.47,-0.4087,8520.0,978.1238
18,110031.SH,20200721,114.00,120.00,120.00,114.02,115.01,1.01,0.8860,59089.0,6846.7091
19,110031.SH,20200720,112.00,112.00,115.90,111.99,114.00,2.00,1.7857,11555.0,1311.6719

In [33]:
df.head()

,ts_code,trade_date,pre_close,open,high,low,close,change,pct_chg,vol,amount
0,110031.SH,20200814,112.82,112.36,113.37,112.36,112.70,-0.12,-0.1064,1974.0,222.9056
1,110031.SH,20200813,112.42,112.78,112.99,112.53,112.82,0.40,0.3558,1690.0,190.4889
2,110031.SH,20200812,112.69,112.80,113.17,112.30,112.42,-0.27,-0.2396,2832.0,319.3778
3,110031.SH,20200811,113.00,113.40,113.95,112.61,112.69,-0.31,-0.2743,4268.0,484.2775
4,110031.SH,20200810,112.49,112.99,114.12,112.70,113.00,0.51,0.4534,2534.0,287.1339

In [40]:
df.describe()

,pre_close,open,high,low,close,change,pct_chg,vol,amount
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,112.861000,113.256000,114.329000,112.270500,112.896000,0.035000,0.034270,10204.300000,1161.645935
std,0.870256,1.748637,1.723393,0.746863,0.847587,0.912114,0.809697,12481.216633,1445.392399
min,111.450000,111.980000,112.760000,111.100000,111.450000,-1.450000,-1.279900,1690.000000,190.488900
25%,112.390000,112.342500,113.097500,111.842500,112.472500,-0.530000,-0.463925,3825.250000,432.232475
50%,112.735000,112.790000,113.940000,112.165000,112.735000,-0.165000,-0.146350,7515.500000,844.863950
75%,113.072500,113.425000,114.827500,112.550000,113.072500,0.427500,0.380500,10532.750000,1198.977350
max,115.010000,120.000000,120.000000,114.020000,115.010000,2.000000,1.785700,59089.000000,6846.709100

In [41]:
df.loc[:, 'vol'].mean()

10204.3

In [4]:
from wxpy import *
bot = Bot()

# 机器人账号自身
myself = bot.self

# 向文件传输助手发送消息
bot.file_helper.send('Hello from wxpy!')

Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.

KeyError: 'pass_ticket'