In [1]:
import baostock as bs
import pandas as pd

In [2]:
lg = bs.login()

login success!

In [16]:
rs = bs.query_history_k_data_plus("sz.127010",
    "date",
    start_date='2019-05-01', end_date='2019-06-05', 
    frequency="d", adjustflag="3") #frequency="d"取日k线，adjustflag="3"默认不复权
print('query_history_k_data_plus respond error_code:'+rs.error_code)
print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

query_history_k_data_plus respond error_code:0
query_history_k_data_plus respond  error_msg:success

In [17]:
data_list = []
while (rs.error_code == '0') & rs.next():
    # 获取一条记录，将记录合并在一起
    data_list.append(rs.get_row_data())
result = pd.DataFrame(data_list, columns=rs.fields)

In [18]:
result

Empty DataFrame
Columns: [date]
Index: []

In [19]:
import tushare as ts

In [20]:
ts.set_token('047e2bcae2ea6c2f6f225eeb62087d27e1981988e758c82ba1997971')

In [21]:
pro = ts.pro_api()

In [ ]:
df = pro.daily(ts_code='603912.SH', start_date=start_dt, end_date=end_dt)

In [22]:
df = pro.trade_cal(exchange='', start_date='20190601', end_date='20190605', fields='exchange,cal_date,is_open,pretrade_date', is_open='0')

In [24]:
data = pro.query('stock_basic', exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')

In [26]:
data.head()

     ts_code  symbol  name area industry list_date
0  000001.SZ  000001  平安银行   深圳       银行  19910403
1  000002.SZ  000002   万科A   深圳     全国地产  19910129
2  000004.SZ  000004  国农科技   深圳     生物制药  19910114
3  000005.SZ  000005  世纪星源   深圳     环境保护  19901210
4  000006.SZ  000006  深振业A   深圳     区域地产  19920427

In [30]:
data[data.ts_code=='127009.SH']

Empty DataFrame
Columns: [ts_code, symbol, name, area, industry, list_date]
Index: []

In [33]:
data[data.name.str.contains('债')]

Empty DataFrame
Columns: [ts_code, symbol, name, area, industry, list_date]
Index: []

In [35]:
print(ts.__version__)

1.2.35

In [40]:
df = ts.new_cbonds(default=0)

#######

In [41]:
df

,bcode,bname,scode,sname,xcode,amount,marketprice,convprice,firstdayprice,ipo_date,issue_date,ballot,return,perreturn
0,113537,文灿转债,603348,文灿股份,754348,8.00,NaN,19.93,NaN,2019-06-10,NaN,NaN,NaN,NaN
1,123026,中环转债,300692,中环环保,370692,2.90,NaN,12.31,NaN,2019-06-10,NaN,NaN,NaN,NaN
2,128068,和而转债,002402,和而泰,072402,5.47,NaN,9.09,NaN,2019-06-04,NaN,0.08 %,NaN,120.58
3,113536,三星转债,603578,三星新材,754578,1.92,NaN,19.75,NaN,2019-05-31,NaN,0.03 %,NaN,327.77
4,113535,大业转债,603278,大业股份,754278,5.00,100.63,12.56,101.59,2019-05-09,2019-06-03,0.03 %,0.00 %,288.79
5,128067,一心转债,002727,一心堂,072727,6.03,106.15,27.28,116.70,2019-04-19,2019-05-17,0.01 %,0.00 %,1149.32
6,128066,亚泰转债,002811,亚泰国际,072811,4.80,96.53,17.49,98.31,2019-04-17,2019-05-14,0.01 %,0.00 %,1175.77
7,110058,永鼎转债,600105,永鼎股份,733105,9.80,94.02,6.50,95.56,2019-04-16,2019-05-08,0.01 %,0.00 %,695.35
8,128065,雅化转债,002497,雅化集团,072497,8.00,93.49,8.98,96.05,2019-04-16,2019-05-10,0.06 %,0.00 %,158.43
9,127013,创维转债,000810,创维数字,070810,10.40,96.63,11.56,99.88,2019-04-15,2019-05-16,0.03 %,0.00 %,383.77
10,113026,核能转债,601985,中国核电,783985,78.00,101.96,6.32,102.71,2019-04-15,2019-05-08,0.03 %,0.00 %,323.12
11,113025,明泰转债,601677,明泰铝业,783677,18.39,96.62,11.49,96.94,2019-04-10,2019-05-07,0.03 %,0.00 %,328.31
12,113534,鼎胜转债,603876,鼎胜新材,754876,12.54,94.64,20.80,96.65,2019-04-09,2019-04-30,0.02 %,0.00 %,481.59
13,113024,核建转债,601611,中国核建,783611,29.96,100.22,9.93,103.00,2019-04-08,2019-04-26,0.02 %,0.00 %,502.39
14,128064,司尔转债,002538,司尔特,072538,8.00,95.20,6.15,99.39,2019-04-08,2019-05-07,0.02 %,0.00 %,490.99
15,128063,未来转债,002631,德尔未来,072631,6.30,101.75,8.68,122.40,2019-04-03,2019-04-24,0.02 %,0.00 %,650.80
16,113533,参林转债,603233,大参林,754233,10.00,111.30,36.50,107.50,2019-04-03,2019-04-24,0.05 %,0.00 %,183.21
17,113532,海环转债,603817,海峡环保,754817,4.60,100.00,7.80,106.51,2019-04-02,2019-04-24,0.02 %,0.00 %,NaN
18,128062,亚药转债,002370,亚太药业,072370,9.65,99.00,16.25,106.81,2019-04-02,2019-04-24,NaN,NaN,NaN
19,110057,现代转债,600420,现代制药,733420,16.16,103.86,10.09,106.39,2019-04-01,2019-04-30,0.04 %,0.00 %,NaN
20,113531,百姓转债,603883,老百姓,754883,3.27,106.82,60.59,108.73,2019-03-29,2019-04-22,0.03 %,0.00 %,NaN
21,123025,精测转债,300567,精测电子,370567,3.75,104.20,50.25,114.90,2019-03-29,2019-04-19,0.02 %,0.00 %,479.76
22,128061,启明转债,002439,启明星辰,072439,10.45,105.90,28.29,110.90,2019-03-27,2019-04-24,0.01 %,0.00 %,717.55
23,113530,大丰转债,603081,大丰实业,754081,6.30,96.11,16.76,104.40,2019-03-27,2019-04-18,0.02 %,0.00 %,NaN
24,128060,中装转债,002822,中装建设,072822,5.25,100.31,6.24,105.73,2019-03-26,2019-04-15,0.05 %,0.00 %,196.53
25,127012,招路转债,001965,招商公路,071965,50.00,100.07,9.34,100.00,2019-03-22,2019-04-30,NaN,NaN,NaN
26,123023,迪森转债,300335,迪森股份,370335,6.00,97.10,7.19,109.37,2019-03-20,2019-04-16,0.02 %,0.00 %,463.73
27,110056,亨通转债,600487,亨通光电,733487,17.33,96.30,21.64,111.59,2019-03-19,2019-04-16,0.02 %,0.00 %,553.61
28,123024,岱勒转债,300700,岱勒新材,370700,2.10,96.00,24.90,109.00,2019-03-19,2019-04-17,0.02 %,0.00 %,618.68
29,110054,通威转债,600438,通威股份,733438,50.00,120.59,12.28,119.90,2019-03-18,2019-04-10,0.01 %,0.00 %,901.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,125959,首钢转债,000959,首钢股份,070959,20.00,205.00,2.97,102.20,2003-12-16,2003-12-31,18.45 %,0.58 %,NaN
279,110001,邯钢转债,600001,邯郸钢铁,733001,20.00,182.00,3.36,103.55,2003-11-26,2003-12-11,13.28 %,0.53 %,0.75
280,100196,复星转债,600196,复星医药,733196,9.50,138.20,5.03,99.00,2003-10-28,2003-11-17,25.47 %,-0.03 %,0.39
281,100096,云化转债,600096,云天化,733096,4.10,147.21,5.80,100.12,2003-09-10,2003-09-25,0.80 %,0.00 %,12.49
282,125936,华西转债,000936,华西村,070936,4.00,143.98,2.70,100.68,2003-09-01,2003-09-16,0.70 %,0.01 %,14.34
283,100117,西钢转债,600117,西宁特钢,733117,4.90,158.00,4.85,103.31,2003-08-11,2003-08-26,0.76 %,0.03 %,13.17
284,100795,国电转债,600795,国电电力,733795,20.00,211.88,2.27,108.04,2003-07-18,2003-08-01,0.35 %,0.03 %,28.73
285,100236,桂冠转债,600236,桂冠电力,733236,8.00,128.50,5.77,103.00,2003-06-30,2003-07-15,1.36 %,0.05 %,7.37
286,100567,山鹰转债,600567,山鹰纸业,733567,2.50,120.37,2.46,102.24,2003-06-16,2003-07-01,1.11 %,0.02 %,9.02
287,100726,华电转债,600726,华电能源,733726,8.00,299.98,3.10,108.00,2003-06-03,2003-06-18,0.63 %,0.04 %,15.95
288,125630,铜都转债,000630,铜陵有色,070630,7.60,112.40,4.45,109.45,2003-05-21,2003-06-04,0.89 %,0.08 %,11.17
289,125930,丰原转债,000930,丰原生化,070930,5.00,145.01,2.40,104.29,2003-04-24,2003-05-20,1.36 %,0.07 %,7.36
290,100177,雅戈转债,600177,雅戈尔,733177,11.90,119.23,3.35,109.88,2003-04-03,2003-04-21,0.50 %,0.04 %,19.87
291,100016,民生转债,600016,民生银行,733016,40.00,98.68,2.39,100.01,2003-02-27,2003-03-18,87.86 %,-0.11 %,0.11
292,125629,钢钒转债,000629,攀钢钢钒,070629,16.00,144.50,5.64,NaN,2003-01-22,2003-02-17,100.00 %,NaN,NaN
293,125729,燕京转债,000729,燕京啤酒,070729,7.00,129.80,21.66,NaN,2002-10-16,2002-10-31,100.00 %,NaN,NaN
294,100087,水运转债,600087,长航油运,733087.0,3.20,205.10,5.41,NaN,2002-08-13,2002-08-28,79.46 %,NaN,0.13
295,125002,万科转债,000002,万科A,70002.0,15.00,145.33,5.85,NaN,2002-06-13,2002-06-28,38.19 %,NaN,0.26
296,100220,阳光转债,600220,江苏阳光,733220.0,8.30,101.99,3.80,NaN,2002-04-18,2002-05-16,7.19 %,NaN,1.39
297,125898,鞍钢转债,000898,鞍钢股份,5898.0,15.00,116.65,2.83,99.20,2000-03-17,2000-04-17,79.27 %,0.79 %,0.13
298,100009,机场转债,600009,上海机场,733009.0,13.50,153.85,7.69,101.06,2000-03-02,2000-03-16,4.71 %,-4.62 %,2.12
299,125301,丝绸转债,000301,丝绸股份,5301.0,2.00,303.59,4.10,203.80,1998-08-28,1998-09-15,1.25 %,1.26 %,NaN
300,100001,南化转债,600301,南化股份,733001.0,1.50,269.70,4.56,229.00,1998-08-03,1998-09-02,0.14 %,0.18 %,73.55
301,125009,宝安转券,000009,中国宝安,000nan,5.00,NaN,19.39,NaN,NaN,1993-02-10,NaN,NaN,NaN
302,110488,天药转债,600488,天药股份,000nan,3.90,189.73,4.33,107.18,NaN,2006-11-10,NaN,NaN,NaN
303,110021,上电转债,600021,上海电力,000nan,10.00,226.58,4.43,113.79,NaN,2006-12-19,NaN,NaN,NaN
304,125024,招商转债,000024,招商地产,000nan,15.10,290.37,13.09,122.00,NaN,2006-09-11,NaN,NaN,NaN
305,120002,18中原EB,000719,中原传媒,000nan,6.20,110.60,10.05,105.80,NaN,2019-01-11,NaN,NaN,NaN
306,132013,17宝武EB,600019,宝钢股份,000nan,150.00,99.60,10.00,97.01,NaN,2017-12-28,NaN,NaN,NaN
307,115002,国安债1,000839,中信国安,000nan,17.00,99.88,NaN,70.50,NaN,2007-09-25,NaN,NaN,NaN

In [42]:
df.describe()

,bcode,amount,marketprice,convprice,firstdayprice,perreturn
count,308.000000,308.000000,301.000000,287.000000,282.000000,267.000000
mean,118960.792208,25.580162,126.488538,13.279129,108.659078,324.926404
std,8546.700044,52.732693,45.524804,11.878813,18.339708,1022.143294
min,100001.000000,1.140000,91.010000,1.690000,68.750000,0.000000
25%,110357.250000,5.752500,99.960000,6.150000,99.562500,12.780000
50%,123005.500000,10.000000,106.700000,9.260000,106.450000,37.010000
75%,127010.250000,21.132500,138.590000,15.880000,116.050000,165.715000
max,132015.000000,400.000000,366.000000,81.490000,229.000000,7856.420000

In [54]:
con=ts.get_apis()
dfs =  ts.bar('127009', conn=con)

In [55]:
dfs

,code,open,close,high,low,vol,amount,p_change
datetime,,,,,,,,
2019-06-06,127009,133.990,130.199,134.150,129.601,329.0,43427128.0,-1.36
2019-06-05,127009,137.000,132.000,137.647,131.000,323.0,43671884.0,-1.42
2019-06-04,127009,132.000,133.899,136.750,129.010,568.0,76246440.0,1.59
2019-06-03,127009,145.690,131.800,146.299,131.200,554.0,76386232.0,-9.10
2019-05-31,127009,146.000,145.000,146.886,144.010,496.0,72211672.0,-0.46
2019-05-30,127009,144.000,145.677,147.800,142.690,1118.0,163171536.0,0.79
2019-05-29,127009,143.050,144.533,147.000,143.030,752.0,109166344.0,1.05
2019-05-28,127009,139.590,143.030,149.888,138.900,1928.0,279063840.0,2.87
2019-05-27,127009,136.500,139.039,140.370,136.500,796.0,110721368.0,2.31
2019-05-24,127009,133.500,135.900,139.000,133.500,863.0,117726472.0,1.42
2019-05-23,127009,134.499,133.999,137.200,133.020,344.0,46830832.0,-0.74
2019-05-22,127009,134.250,135.000,136.970,134.000,263.0,35624348.0,0.75
2019-05-21,127009,130.499,134.000,135.020,130.270,396.0,52772184.0,2.67
2019-05-20,127009,130.900,130.509,130.900,127.500,218.0,28234784.0,-0.06
2019-05-17,127009,136.630,130.585,139.650,130.002,769.0,104807232.0,-4.42
2019-05-16,127009,138.400,136.620,139.011,136.160,297.0,40798572.0,-1.00
2019-05-15,127009,133.980,138.000,139.600,133.485,1245.0,170726288.0,4.55
2019-05-14,127009,130.360,132.000,134.030,130.200,321.0,42568196.0,0.75
2019-05-13,127009,131.880,131.020,133.945,130.210,267.0,35425296.0,-1.50
2019-05-10,127009,126.550,133.020,134.290,125.010,1332.0,174344128.0,6.83
2019-05-09,127009,126.400,124.512,127.797,124.300,203.0,25650824.0,-1.42
2019-05-08,127009,124.677,126.311,128.498,123.180,468.0,59590084.0,0.02
2019-05-07,127009,126.000,126.280,129.500,124.025,680.0,86250264.0,0.77
2019-05-06,127009,129.010,125.320,130.400,120.100,354.0,45415696.0,-6.23
2019-04-30,127009,135.500,133.650,136.965,130.500,334.0,45064068.0,-0.85
2019-04-29,127009,139.899,134.800,142.360,133.948,778.0,107742520.0,-0.55
2019-04-26,127009,139.880,135.550,140.200,135.010,254.0,35101660.0,-1.97
2019-04-25,127009,154.400,138.280,155.316,138.000,403.0,59033000.0,-11.04
2019-04-24,127009,155.500,155.432,159.900,152.120,364.0,56655936.0,0.29
2019-04-23,127009,157.980,154.980,165.000,153.560,659.0,106014368.0,-1.85
...,...,...,...,...,...,...,...,...
2019-04-03,127009,145.499,144.250,147.000,143.501,111.0,16136421.0,-0.93
2019-04-02,127009,146.200,145.601,147.799,143.000,255.0,37317916.0,0.41
2019-04-01,127009,139.897,145.000,146.600,139.600,671.0,96681368.0,3.94
2019-03-29,127009,136.000,139.500,141.430,133.301,676.0,93576792.0,-0.36
2019-03-28,127009,140.150,140.000,145.777,138.000,1115.0,158231168.0,-3.12
2019-03-27,127009,139.000,144.502,145.000,133.980,1926.0,270231392.0,6.25
2019-03-26,127009,135.601,136.000,137.888,131.230,204.0,27682032.0,0.29
2019-03-25,127009,137.170,135.600,139.400,135.201,203.0,27969994.0,-1.86
2019-03-22,127009,138.400,138.170,139.850,136.000,124.0,17147104.0,-0.60
2019-03-21,127009,135.400,139.000,141.500,135.203,732.0,101274152.0,2.66
2019-03-20,127009,137.847,135.400,138.020,133.220,198.0,27043414.0,-1.78
2019-03-19,127009,140.001,137.850,140.999,136.457,703.0,97404736.0,-1.23
2019-03-18,127009,138.600,139.560,144.660,134.000,2317.0,324701888.0,4.85
2019-03-15,127009,121.668,133.100,133.200,121.668,1506.0,194424720.0,10.21
2019-03-14,127009,123.000,120.770,123.999,117.301,130.0,15666861.0,-1.97
2019-03-13,127009,124.000,123.200,127.300,122.999,150.0,18885866.0,-0.65
2019-03-12,127009,125.578,124.000,127.880,122.220,442.0,55133684.0,0.34
2019-03-11,127009,115.150,123.580,124.950,115.150,273.0,33425614.0,6.50
2019-03-08,127009,119.400,116.041,119.470,115.500,277.0,32575884.0,-2.98
2019-03-07,127009,119.341,119.610,121.180,118.001,201.0,24165566.0,0.23
2019-03-06,127009,119.000,119.330,121.201,118.501,528.0,7634033.0,0.28
2019-03-05,127009,118.199,119.000,119.600,117.100,368.0,6353789.5,0.68
2019-03-04,127009,116.000,118.200,119.039,116.000,226.0,26818166.0,1.90
2019-03-01,127009,115.996,116.000,116.300,115.602,101.0,11748463.0,0.00
2019-02-28,127009,115.641,115.996,116.997,115.641,384.0,6307342.5,0.31
2019-02-27,127009,114.000,115.640,119.666,114.000,197.0,23023896.0,-0.88
2019-02-26,127009,117.510,116.670,119.500,112.601,88.0,10439471.0,-1.17
2019-02-25,127009,114.500,118.047,118.800,114.300,334.0,38818184.0,3.46
2019-02-22,127009,114.520,114.100,114.520,112.889,632.0,71826184.0,-0.37
2019-02-21,127009,112.100,114.520,115.620,111.800,3325.0,376905216.0,NaN